const carName = 'Lamborgini';
let maxCarSpeed = '320 km/h';
let carOwner = 'Owner';
alert(carName);
alert(maxCarSpeed);
alert(carOwner);
maxCarSpeed = '325 km/h';
carOwner = 'Вячеслав';
console.log('У машины изменилась максимальная скорость', maxCarSpeed);
console.log('У машины изменился владелец', carOwner);
maxCarSpeed = '310 km/h';
carOwner = 'Станислав';
console.log('У машины изменилась максимальная скорость', maxCarSpeed);
console.log('У машины изменился владелец', carOwner);
maxCarSpeed = '340 km/h';
carOwner = 'Дмитрий';
console.log('У машины изменилась максимальная скорость', maxCarSpeed);
console.log('У машины изменился владелец', carOwner);